### ISSUE TITLE
Make site name mapping configurable

### ISSUE THREAD

**Issue by larkgz** [digitalutsc/islandora_site_name#1]
Currently, this module only indexes site name from the HTML title value of the nodes rather than the Solr site field. It does this by checking for the value after `|` in the title. If the title is not in this form, the site name will not be indexed.

It would be good if site titles could be set manually somehow.

**Comment by larkgz** [comment]
One suggested method was to have a pop-up during indexing, but I could not figure out a way to do this. 

I tried to have it so that site names could be mapped to site URLs. The main problem I had is that the Solr site field is not accessible from the Content datasource. It seems that it can only be accessed directly through the Solr Document datasource. I tried adding it to a REST API view, but the Solr Document datasource does not seem to map to node ids with that view so I wasn't sure how to access its data.

**Comment by Natkeeran** [comment]
This usecase is not longer needed.
